config/routes.rb
KurbiBeta::Application.routes.draw do
  get "sessions/new"

  #resources :members do
  #  resources :journal, :history
  #end	
  resources :members
  resources :sessions,   :only => [:new, :create, :destroy]
  
  root :to => 'pages#home'
  match '/public/about',   :to => 'pages#about',      :as => 'about'
  match '/public/home',    :to => 'pages#home',       :as => 'home'
  match '/public/contact', :to => 'pages#contact',    :as => 'contact' 
  match '/member/signup',  :to => 'members#new',      :as => 'signup'
  match '/member/signin',  :to => 'sessions#new',     :as => 'signin'
  match '/member/signout', :to => 'sessions#destroy', :as => 'signout'
  
  # root :to => 'pages#index'
  #   
  #   match '/public/home/:page', :to => 'pages#index'
  #   
  #   match '/public/about', :to => 'pages#about', :as => 'about'
  #  match '/public/home', :to => 'pages#home', :as => 'home'
  #   match '/public/contact', :to => 'pages#contact', :as => 'contact'
  #   
  #   match '/public/:page', :to => 'pages#index'	
     
end

app/models/actions.rb
class Actions < ActiveRecord::Base
  has_and_belongs_to_many :people
end

app/models/addresses.rb
class Addresses < ActiveRecord::Base
  has_and_belongs_to_many :people
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
	has_and_belongs_to_many :patients 
	has_one :days
	has_one :severity
end

app/models/days.rb
class Days < ActiveRecord::Base
	has_many :daily_records
end

app/models/doctors.rb
class Doctors < ActiveRecord::Base
	has_one :persons
end

app/models/employees.rb
class Employees < ActiveRecord::Base
	has_one :persons
end

app/models/member.rb
class Member < ActiveRecord::Base
	  has_many :patient_symptom_search
	  has_many :user_defined_symptoms
	  has_one :people, :dependent => :destroy
	  
	  	  
	  attr_accessible :email, :password, :password_confirmation
	  
	  attr_accessor :password
	  before_save :encrypt_password
	  
	  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	  validates :email,    :presence => true,
	                       :format   => { :with => email_regex },
	                       :uniqueness => { :case_sensitive => false }
	  validates :password, :presence => true,
	  					   :confirmation => true,
	  					   :length => { :within => 6..40 }
	  					   	  
	  def self.authenticate(email, password)
	    member = find_by_email(email)
	    if member && member.password_hash == BCrypt::Engine.hash_secret(password, member.password_salt)
	      member
	    else
	      nil
	    end
	  end
	  
	  def self.authenticate_with_salt(id, cookie_salt)
	  	member = find_by_id(id)
	  	(member && member.password_salt == cookie_salt) ? member : nil
	  end
	  
	  def encrypt_password
	    if password.present?
	      self.password_salt = BCrypt::Engine.generate_salt
	      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	    end
	  end
	  	
end

app/models/messages.rb
class Messages < ActiveRecord::Base
	has_and_belongs_to_many :people
end

app/models/pages.rb
class Pages < ActiveRecord::Base
end

app/models/patients.rb
class Patients < ActiveRecord::Base
	has_one :people
	has_many :patient_symptom_search
	has_many :user_defined_symptoms
end

app/models/people.rb
class People < ActiveRecord::Base
	attr_accessible 
		:first_name,
		:last_name,
		:birthday,
		:location, 
		:race, 
		:sex,
		:bio,
		:first_occurrence,
		:diagnosed, 
		:condition,
		:doctor, 
		:medications, 
		
  has_and_belongs_to_many :actions
  has_and_belongs_to_many :addresses
  has_and_belongs_to_many :predefined_symptoms
  has_and_belongs_to_many :disease_profiles
  has_and_belongs_to_many :roles
  belongs_to :member
  
  
end

app/models/roles.rb
class Roles < ActiveRecord::Base
  has_and_belongs_to_many :people
end

app/models/search_queries.rb
class SearchQueries < ActiveRecord::Base
  has_many :searches
end

app/models/searches.rb
class Searches < ActiveRecord::Base
  has_one :search_queries
end

app/models/severity.rb
class Severity < ActiveRecord::Base
  has_one :predefined_symptoms
  has_one :patients
  has_one :daily_record
end

app/models/system_errors.rb
class SystemErrors < ActiveRecord::Base
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def signin_btn
		image_tag("kurbi-signin-btn.png")
	end
	
	def signout_btn
		image_tag("kurbi-signout-btn.png")
	end
	
	def kurbi_pic
		image_tag("kurbi-pic.png")
	end
	
	def wes_pic 
		image_tag("wes-pic.gif")
	end
	
	def steve_pic
		image_tag("steve-pic.gif")
	end
	
	def david_pic
		image_tag("dave-pic.gif")
	end
	
	def matt_pic
		image_tag("matt-pic.gif")
	end
	
	def twitter
		image_tag("twitter.gif", :alt => "Go Kurbi Twitter")
	end
	
	def tumblr
		image_tag("tumblr.gif", :alt => "Kurbi Mobile Health Tumblr Blog")
	end
	
	def facebook 
		image_tag("facebook.gif", :alt => "Kurbi Mobile Health Facebook Profile")
	end
	
	def home_image
		image_tag("main-image.png")
	end
end

app/views/layouts/_footer.html.erb
<footer class="top-shadow">
	<section id="footer-bar">
		<div id="sm-icons">
		<nav>
			<ul>
				<li>
				<%= link_to twitter, 'http://twitter.com/gokurbi', :target => '_blank' %>
				</li>
				<li>
				<%= link_to tumblr, 'http://gokurbi.tumblr.com/', :target => '_blank' %>
				</li>
				<li>
				<%= link_to facebook, 'https://www.facebook.com/pages/Kurbi/248340778541148', :target => '_blank' %>
				</li>
			</ul>
		</nav>
		</div><!--#sm-icons-->
	
		<div id="footer-nav">
		<nav>
			<ul>
				<li><%= link_to "about us", about_path %></li>
				<li>
					<%= link_to "what's new", 'http://gokurbi.tumblr.com/', 
					:target => '_blank' %>
				</li>
				<li><%= link_to "faq's", '#' %></li>
				<li><%= link_to "user agreement", '#' %></li>
				<li><%= link_to "contact", contact_path %></li>	
			</ul>
		</nav>
		</div><!--#footer-nav-->
	</section><!--#footer-bar-->
</footer>

app/views/layouts/_header.html.erb
<header class="bottom-shadow">

	<% if signed_in? %>
		<%= link_to logo, @member %>
		
		<nav>
			<%= link_to signout_btn, signout_path %>
		</nav>
	<% else %>
		<%= link_to logo, root_path %>
		
		<nav>
			<%= link_to signin_btn, signin_path %>
		</nav>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrap">
		<%= render 'layouts/header' %>
		<div id="main">
			<% flash.each do |key, value| %>
			<div class="flash <%= key %> round"><%= value %></div>
			<% end %>
			<%= yield %>
		</div><!--#main-->
	</div><!--#wrap-->
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/_form.html.erb
<div id="form">
<form id="form3" name="form3" class="wufoo topLabel page" autocomplete="off" enctype="multipart/form-data" method="post" novalidate
action="https://rightside.wufoo.com/forms/q7x3z9/#public">

<ul>
<li id="foli3" class="notranslate      ">
<label class="desc" id="title3" for="Field3">
First Name
<span id="req_3" class="req">*</span>
</label>
<div>
<input id="Field3" name="Field3" type="text" class="field text medium" value="" maxlength="255" tabindex="1" onkeyup="" required />
</div>
</li><li id="foli4" class="notranslate      ">
<label class="desc" id="title4" for="Field4">
Last Name
<span id="req_4" class="req">*</span>
</label>
<div>
<input id="Field4" name="Field4" type="text" class="field text medium" value="" maxlength="255" tabindex="2" onkeyup="" required />
</div>
</li><li id="foli5" class="notranslate      ">
<label class="desc" id="title5" for="Field5">
Email
<span id="req_5" class="req">*</span>
</label>
<div>
<input id="Field5" name="Field5" type="email" spellcheck="false" class="field text medium" value="" maxlength="255" tabindex="3" required /> 
</div>
</li>
<li id="foli108" class="notranslate       ">
<label class="desc" id="title108" for="Field108">
Which are you?
<span id="req_108" class="req">*</span>
</label>
<div>
<select id="Field108" name="Field108" class="field select medium" tabindex="7" > 
<option value="Person Living with MS" selected="selected">
Person Living with MS
</option>
<option value="Care-Giver" >
Care-Giver
</option>
<option value="Physical Therapist" >
Physical Therapist
</option>
<option value="Personal Trainer" >
Personal Trainer
</option>
<option value="Work with MS Society" >
Work with MS Society
</option>
<option value="Other" >
Other
</option>
</select>
</div>
</li>
<li id="foli109" 
class="notranslate      "><label class="desc" id="title109" for="Field109">
Comments
</label>

<div>
<textarea id="Field109" 
name="Field109" 
class="field textarea medium" 
spellcheck="true" 
rows="10" cols="50" 
tabindex="8" 
onkeyup=""
 ></textarea>

</div>
</li> <li class="buttons ">
<div>

<input id="saveForm" name="saveForm" class="btTxt round" type="submit" value="Submit"
 /></div>
</li>

<li class="hide">
<label for="comment">Do Not Fill This Out</label>
<textarea name="comment" id="comment" rows="1" cols="1"></textarea>
<input type="hidden" id="idstamp" name="idstamp" value="5Nbkc3RVyHtxW7wOrTtZ23TzRQOHebR6P8VPyTG6AIo=" />
</li>
</ul>
</form> 
</div><!--#form-->

app/views/pages/_team.html.erb
<div id="team_info">
		<h2>Meet Our Team</h2>
		<div id="left-profiles">
			<%= link_to kurbi_pic, 'http://twitter.com/gokurbi', :target => '_blank' %>
			<h3>Kurbi</h3>
			<p>"As CEO, Chief Encouragement Officer, I am here to help guide you through our application, and of course be your #1 fan."
			</p>
		
		<%= link_to wes_pic, 'http://twitter.com/wes_garnett', :target => '_blank' %>
		<h3>Wesley Garnett, Jr.</h3>
		<p>"My Mom was diagnosed with MS 8 years ago; my great uncle and cousin soon after her. I'm involved with Kurbi because I believe it will eventually help researchers find a cure."
		</p>

		<%= link_to steve_pic, 'http://twitter.com/steve_roettger', :target => '_blank' %>
		<h3>Steve Roettger</h3>
		<p>"I feel that by logging this data (symptom management & physical activity) on a daily basis, we can better learn about MS progression, and ultimately use this learning to improve overall quality of life."
		</p>
		</div><!--#upperleft-lower-content-->
		
		<div id="right-profiles">
		<%= link_to david_pic, 'http://twitter.com/davidclizbe', :target => '_blank' %>
		<h3>David Clizbe, M.S.</h3>
		<p>"As a biomechanist and researcher of neuromuscular control, my interest in Kurbi is its unique ability to improve collecting, analyzing, and integrating healthcare data into new and meaningful solutions." 
		</p>

		<%= link_to matt_pic, 'http://twitter.com', :target => '_blank' %>
		<h3>Matt Eckman</h3>
		<p>"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor." 
		</p>

		<%= link_to kurbi_pic, 'http://twitter.com', :target => '_blank' %>
		<h3>Gregg Noll</h3>
		<p>"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor." 
		</p>
		</div>
</div><!--.team_info-->

app/views/pages/about.html.erb
<!--This is the about page to give a brief description & to show the members of our team-->
<section id="about-section">
	<h2>About Kurbi</h2>
	<div id="about-text">
	<p>Symptom management and physical activity are two of the hottest topics in the Multiple Sclerosis world, and Kurbi was created to help people living with the condition to more easily achieve both.</p>
	<p>If you are living with the condition or know someone that is, you are most likely familiar with the struggle to communicate how MS is affecting you and/or your loved one. Kurbi is here to let you know you are not alone, and that together, we can help each other, care-providers, and researchers understand more about MS than ever before possible.</p>
	<p>Up until now, the daily experiences of how MS affects people outside of clinical trials has been a mystery. We developed Kurbi with the belief that if people could easily tell us what they were experiencing we would inevitably find important, world changing answers about MS in the data.</p>
	</div><!--#about-text-->
	
	<%= render 'pages/team' %>
</section>

app/views/pages/contact.html.erb
<!--
This is the global contact page, where visitors to the site can send an email to info@gokurbi.com
-->
<section id="contact-section">
<h2>Contact</h2>
<p>Thanks for your interest in the Kurbi App. We look forward to getting to know you soon!</p>

<section>
	<%= render 'pages/form' %>
</section>
</section><!--#contact-section-->

app/views/pages/home.html.erb
<%= render 'shared/home_sidenav' %>

<div id="main-home" class="mid-shadow">
<h1>Track, Manage & Understand Your Health</h1>
	<section id="home-left">
		<p>Kurbi is a breakthrough web application that helps people living with chronic disease to more easily communicate the daily challenges of their symptoms to care-providers in-between scheduled visits.</p>
		<div class="actions">
		  <%= link_to "Sign up!", signup_path, :id => "home-sign-up", :class => "button round" %>
		  <div class="home-link">
		  	<p>Already a user? <%= link_to "Sign in now.", signin_path %></p>
		  </div><!--.home-link-->
		</div><!--.actions-->				
	</section><!--#home-left-->
	
	<section id="home-right">
		<%= home_image %>				
	</section><!--#home-right-->
</div><!--#main-home-->

app/views/shared/_error_messages.html.erb
<!--This is the shared helper for error messages for all forms in the application-->

<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_home_sidenav.html.erb
<nav id="home-sidebar">
	<ul class="side-nav-style">
		<li class="<%= "current" if params[:controller] == "members" %>">
			<%= link_to "Sign up", signup_path %>
		</li>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
	</ul>
</nav>

app/views/shared/_sidenav.html.erb
<nav id="main-sidebar">
	<ul class="side-nav-style">
		<li class="<%= "current" if params[:controller] == "journals" %>">
			<%= link_to "Journal", "#" %>
		</li>
		<li class="<%= "current" if params[:controller] == "history" %>">
			<%= link_to "History", "#" %>
		</li>
		<li class="<%= "current" if params[:controller] == "members" %>">
			<%= link_to "Profile", "#" %>
		</li>
	</ul>
</nav>