config/routes.rb
KurbiBeta::Application.routes.draw do
  get "sessions/new"

  #resources :members do
  #  resources :journal, :history
  #end	
  resources :members
  resources :sessions,   :only => [:new, :create, :destroy]
  
  root :to => 'pages#home'
  match '/public/about',   :to => 'pages#about',      :as => 'about'
  match '/public/home',    :to => 'pages#home',       :as => 'home'
  match '/public/contact', :to => 'pages#contact',    :as => 'contact' 
  match '/member/signup',  :to => 'members#new',      :as => 'signup'
  match '/member/signin',  :to => 'sessions#new',     :as => 'signin'
  match '/member/signout', :to => 'sessions#destroy', :as => 'signout'
  
  # root :to => 'pages#index'
  #   
  #   match '/public/home/:page', :to => 'pages#index'
  #   
  #   match '/public/about', :to => 'pages#about', :as => 'about'
  #  match '/public/home', :to => 'pages#home', :as => 'home'
  #   match '/public/contact', :to => 'pages#contact', :as => 'contact'
  #   
  #   match '/public/:page', :to => 'pages#index'	
     
end

app/models/actions.rb
class Actions < ActiveRecord::Base
  has_and_belongs_to_many :people
end

app/models/addresses.rb
class Addresses < ActiveRecord::Base
  has_and_belongs_to_many :people
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
	has_and_belongs_to_many :patients 
	has_one :days
	has_one :severity
end

app/models/days.rb
class Days < ActiveRecord::Base
	has_many :daily_records
end

app/models/doctors.rb
class Doctors < ActiveRecord::Base
	has_one :persons
end

app/models/employees.rb
class Employees < ActiveRecord::Base
	has_one :persons
end

app/models/member.rb
class Member < ActiveRecord::Base
	  has_many :patient_symptom_search
	  has_many :user_defined_symptoms
	  has_one :people, :dependent => :destroy
	  
	  	  
	  attr_accessible :email, :password, :password_confirmation
	  
	  attr_accessor :password
	  before_save :encrypt_password
	  
	  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	  validates :email,    :presence => true,
	                       :format   => { :with => email_regex },
	                       :uniqueness => { :case_sensitive => false }
	  validates :password, :presence => true,
	  					   :confirmation => true,
	  					   :length => { :within => 6..40 }
	  					   	  
	  def self.authenticate(email, password)
	    member = find_by_email(email)
	    if member && member.password_hash == BCrypt::Engine.hash_secret(password, member.password_salt)
	      member
	    else
	      nil
	    end
	  end
	  
	  def self.authenticate_with_salt(id, cookie_salt)
	  	member = find_by_id(id)
	  	(member && member.password_salt == cookie_salt) ? member : nil
	  end
	  
	  def encrypt_password
	    if password.present?
	      self.password_salt = BCrypt::Engine.generate_salt
	      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	    end
	  end
	  	
end

app/models/messages.rb
class Messages < ActiveRecord::Base
	has_and_belongs_to_many :people
end

app/models/pages.rb
class Pages < ActiveRecord::Base
end

app/models/patients.rb
class Patients < ActiveRecord::Base
	has_one :people
	has_many :patient_symptom_search
	has_many :user_defined_symptoms
end

app/models/people.rb
class People < ActiveRecord::Base
	attr_accessible 
		:first_name,
		:last_name,
		:birthday,
		:location, 
		:race, 
		:sex,
		:bio,
		:first_occurrence,
		:diagnosed, 
		:condition,
		:doctor, 
		:medications, 
		
  has_and_belongs_to_many :actions
  has_and_belongs_to_many :addresses
  has_and_belongs_to_many :predefined_symptoms
  has_and_belongs_to_many :disease_profiles
  has_and_belongs_to_many :roles
  belongs_to :member
  
  
end

app/models/roles.rb
class Roles < ActiveRecord::Base
  has_and_belongs_to_many :people
end

app/models/search_queries.rb
class SearchQueries < ActiveRecord::Base
  has_many :searches
end

app/models/searches.rb
class Searches < ActiveRecord::Base
  has_one :search_queries
end

app/models/severity.rb
class Severity < ActiveRecord::Base
  has_one :predefined_symptoms
  has_one :patients
  has_one :daily_record
end

app/models/system_errors.rb
class SystemErrors < ActiveRecord::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def show
		@member = Member.find(params[:id])
		@title = "Profile"
	end
	
	def new 
		@member = Member.new
		@title = "Sign up"
	end
	
	def create
		@member = Member.new(params[:member])
		if @member.save
			sign_in @member
			flash[:success] = "Hi there! Welcome to Kurbi!"
			redirect_to @member 
		else
			@title = "Sign up"
			render 'new'
		end
	end
	
	def edit
		@member = Member.find(params[:id])
		@title = "Edit Member Settings"
	end
	
	def update
		@member = Member.find(params[:id])
		if @member.update_attributes(params[:member])
			flash[:success] = "Your account settings have been updated."
			redirect_to @member
		else 
			@title = "Edit Member Settings"
			render 'edit'
		end
	end
	
	
end

#Actions
#                     POST   /members(.:format)                             {:action=>"create", :controller=>"members"}
#          new_member GET    /members/new(.:format)                         {:action=>"new", :controller=>"members"}
#         edit_member GET    /members/:id/edit(.:format)                    {:action=>"edit", :controller=>"members"}
#              member GET    /members/:id(.:format)                         {:action=>"show", :controller=>"members"}
#                     PUT    /members/:id(.:format)                         {:action=>"update", :controller=>"members"}
#                     DELETE /members/:id(.:format)                         {:action=>"destroy", :controller=>"members"

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def signin_btn
		image_tag("kurbi-signin-btn.png")
	end
	
	def signout_btn
		image_tag("kurbi-signout-btn.png")
	end
	
	def kurbi_pic
		image_tag("kurbi-pic.png")
	end
	
	def wes_pic 
		image_tag("wes-pic.gif")
	end
	
	def steve_pic
		image_tag("steve-pic.gif")
	end
	
	def david_pic
		image_tag("dave-pic.gif")
	end
	
	def matt_pic
		image_tag("matt-pic.gif")
	end
	
	def twitter
		image_tag("twitter.gif", :alt => "Go Kurbi Twitter")
	end
	
	def tumblr
		image_tag("tumblr.gif", :alt => "Kurbi Mobile Health Tumblr Blog")
	end
	
	def facebook 
		image_tag("facebook.gif", :alt => "Kurbi Mobile Health Facebook Profile")
	end
	
	def home_image
		image_tag("main-image.png")
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(member)
		cookies.permanent.signed[:remember_token] = [member.id, member.password_salt]
		current_member = member
		@current_member = member
	end
	
	def current_member
		@current_member ||= member_from_remember_token
	end
	
	def signed_in?
		return !current_member.nil?
	end
	
	def sign_out
		current_member = nil
		@current_member = nil
		cookies.delete(:remember_token)
	end
	
	def current_member?(member)
		member == current_member
	end
	
	def authenticate
		deny_access unless signed_in?
	end
	
	def deny_access
		store_location
		redirect_to signin_path, :notice => "Please sign in to access this page."
	end
	
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end
	
	private
	
		def member_from_remember_token
			Member.authenticate_with_salt(*remember_token)
		end
		
		def remember_token
			cookies.signed[:remember_token] || [nil,nil]
		end
		
		def store_location
			session[:return_to] = request.fullpath
		end
		
		def clear_return_to
			session[:return_to] = nil
		end
	
	

end

app/views/members/_form_edit.html.erb
<%= form_for(@member) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div><!--.field-->
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div><!--.field-->
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div><!--.field-->
  <div class="actions">
    <%= f.submit "Update", :class => "button round" %>
  </div><!--.actions-->
<% end %>

app/views/members/_form_new.html.erb
<!--This is the 'fields' helper for the new user 'sign up' page-->

<%= render 'shared/error_messages', :object => f.object %>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div><!--.field-->
	
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div><!--.field-->
	
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br/>
		<%= f.password_field :password_confirmation %>
	</div><!--.field-->                                                                                             

app/views/members/edit.html.erb
<%= render 'shared/sidenav' %>

<section id="main-profile" class="mid-shadow">
	<div id="edit_settings_form">
		<h2>Edit Member Settings</h2>
		<%= render 'form_edit' %>
	</div><!--#edit_settings_form-->
</section><!--#main_profile-->

app/views/members/new.html.erb
<!--This is the new user's sign up form page-->
<%= render 'shared/home_sidenav' %>

<section id="main-profile" class="mid-shadow">
	<div id="sign_up_form">
		<h2>Sign up</h2>
		
		<%= form_for(@member) do |f| %>
			<%= render 'form_new', :f => f %>		
			<div class="actions">
				<%= f.submit "Sign up", :class => "button round" %>
			</div>
		<% end %>
		<p>Already a user? <%= link_to "Sign in", signin_path %></p>
	</div><!--#sign_up_form-->
</section><!--#main-profile-->

app/views/members/show.html.erb
<%= render 'shared/sidenav' %>

<section id="main-profile" class="mid-shadow">
	<nav id="profile-nav">
		<ul>
			<li><%= link_to "Watch Tutorial", "#" %></li>
			<li><%= link_to "Your Settings", edit_member_path(current_member) %></li>
			<li><%= link_to "Your Care Team", "#" %></li>
		</ul>
	</nav>

</section>